---
- name: create nginx symlink
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{ django_domain_name }}'
    dest: '/etc/nginx/sites-enabled/{{ django_domain_name }}'
    state: link

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
