all:
  hosts:
    <hosts>
  vars:
    ansible_port: 22
    ansible_user: iraya
    ansible_python_interpreter: /usr/bin/python3
    app_version: 0.1.0
    docker_hub:
      user: myusername
      password: mypassword

    apps_directory: "/home/user/apps"
    debug: 0
    django_runner_replica: 1
    django_redis_cache: "django_redis_cache"
    django_redis_queue: "django_redis_queue"
    django_log_location: "/var/log/django/django.log"
    django_requests_log_location: "/var/log/django/djangorequestlogs.log"
    django_domain_name: "django-web"
    is_ssl: false
    postgres:
      username: djangopostgresuser
      password: djangopostgrespassword
      host: django_db
      dbname: djangodb
    
    deploy_django_app: no
    deploy_elasticsearch: no
    deploy_airflow: no